fix wrong time-series alignment and add WA for StatsForcastAutoARIMA
mindsdb/lightwood pull request #1022
Opened 2022-10-16 14:03 UTC by bachng2017

a proposed fix for time-series alignment error and issue of StatsForcastAutoARIMA
1) see https://github.com/mindsdb/mindsdb/issues/3234 for detail about the alignment issue
2) see https://mindsdbcommunity.slack.com/archives/C037482KJ22/p1665911392587569 for more detail about the issue of 
StatsForcastAutoARIMA

the proposed fix is tested with house-sale tutorial only. It might need more review to consider the impact of the change

2022-10-17 12:15 UTC, ZoranPandovski commented
recheckcla

2022-10-18 11:37 UTC, paxcema commented on lightwood/mixer/sktime.py
> +            all_preds = model.predict(np.arange(start, end)).tolist()[-min_offset:]
Yeah, this workaround will do for now. It may be slightly more compute, but we can remove it once the behavior is fixed in the dependency.

2022-10-18 11:38 UTC, paxcema commented on lightwood/mixer/sktime.py
> +            all_preds = model.predict(np.arange(start, end)).tolist()[-min_offset:]
Yeah, this workaround will do for now. It may be slightly more compute, but we can remove it once the behavior is fixed in the dependency.

2022-10-18 11:42 UTC, paxcema requested changes
Thanks for the PR :)

The workaround is okay. There are two other modifications that I'm not 100% convinced on yet. I will manually test a bit more, but if you have any proof it would be awesome to translate that into a `test` that captures the failing behavior, so that we can catch this next time that the alignment fails. If you can't, then give me some time and I will 1) merge this and 2) add tests on top.

2022-10-18 13:55 UTC, paxcema commented
Update: the test in #1023 leads me to believe the general alignment behavior is correct (`StatsForecast` bug notwithstanding), and unless we have a test to showcase an edge case that justifies the above changes, I'm inclined to not merge those. I will try to find such a test, but in the meantime @bachng2017, it does seem like the issue is in `mindsdb` rather than `lightwood`, so I will check that now.

2022-10-18 15:31 UTC, bachng2017 commented
thanks  @paxcema 
did you check the conversation at https://mindsdbcommunity.slack.com/archives/C037482KJ22/p1665911392587569
from that it  looks like an issue of StatsForcastAutoARIMA for us

2022-10-19 13:28 UTC, paxcema commented
For now, can you please remove the changes in offset indexes?

Just leave the StatsForecast workaround, and I will merge immediately. We can debug the second problem in a separate PR. Thanks!

2022-10-19 13:55 UTC, bachng2017 commented
yes we've just left the StatsForcastAutoARIMA wa there and remove other changes

2022-10-19 14:42 UTC, paxcema commented
Can you try to merge again please? Somehow GitHub thinks the newly added `RandomForest` mixer will be added again, which should not be the case.

2022-10-19 22:38 UTC, bachng2017 commented
tried to merge again, not sure is that OK or not

2022-10-20 12:36 UTC, paxcema commented
Yes, merge is now fine 👍 

There is a failing test, however. I will have to take a closer look on why before merging.

2022-10-20 15:47 UTC, merged

2022-10-21 00:40 UTC, bachng2017 commented
thanks, the merge also very helpful for us.
We will do our own test (manual) with the latest and try to submit other issue (because we think the index issue which we've removed from this PR still be there)