fix mixers for tags
mindsdb/lightwood pull request #288
Opened 2020-09-30 13:08 UTC by maximlopin

2020-09-30 15:41 UTC, George3d6 requested changes
Please keep the booster mixer, since it's a good example mixer and we might want to use it in favor of sklearn for some tasks because training is quicker and in a lot of problems gradient boosters seems to be a very good speed/accuracy intersection

2020-10-01 17:45 UTC, paxcema commented on lightwood/mixers/base_mixer.py
> +                raise ValueError('you must provide encoder to compue accuracy for tags data type')
typo: `compue` -> `compute`

2020-10-01 17:48 UTC, paxcema commented on lightwood/mixers/boost.py
> +                    sample_weight = [weight_map[val] for val in Y_train]
Is `Y_train` defined in this method?

2020-10-01 17:52 UTC, paxcema commented on lightwood/mixers/sklearn_mixer.py
> +                continue
Seems to me like this `continue` is not needed?

2020-10-01 19:26 UTC, paxcema approved these changes

2020-10-02 05:10 UTC, merged